import Link from "next/link";
import { ArrowRight, CheckCircle2, CircleUserRound, Search, XCircle } from "lucide-react";
import { AccountClaimManager } from "@/components/account-claim-manager";
import { StaffPermissionInlineManager } from "@/components/staff-permission-inline-manager";
import { invokeStaffAccountRequest, revokeStaffAccountRequest } from "@/app/staff/actions";
import { loadStaffData } from "@/lib/staff-data";

type SearchParams = Promise<Record<string, string | string[] | undefined>>;
function one(value: string | string[] | undefined) { return Array.isArray(value) ? value[0] ?? "" : value ?? ""; }

export default async function StaffPage({ searchParams }: { searchParams: SearchParams }) {
  const params = await searchParams; const query = one(params.q).trim().toLowerCase(); const account = one(params.account); const page = Math.max(1, Number(one(params.page)) || 1); const data = await loadStaffData();
  const filtered = data.rows.filter((row) => (!query || row.display_name.toLowerCase().includes(query) || (row.employee_code ?? "").toLowerCase().includes(query)) && (!account || account === "claimed" && row.profile_id !== null || account === "unclaimed" && row.profile_id === null));
  const pageSize = 20; const pageCount = Math.max(1, Math.ceil(filtered.length / pageSize)); const rows = filtered.slice((page - 1) * pageSize, page * pageSize);
  const pageLink = (nextPage: number) => { const values = new URLSearchParams(); if (query) values.set("q", query); if (account) values.set("account", account); values.set("page", String(nextPage)); return `/staff?${values}`; };
  return <>
    <header className="mb-6 flex items-center justify-between gap-4"><div><p className="text-xs font-medium uppercase tracking-[0.18em] text-cyan-300/80">People</p><h1 className="mt-1 text-2xl font-semibold text-white">Staff Management</h1><p className="mt-2 text-sm text-slate-400">Staff records are created from approved applications. Save credentials and doorlock entrances from each profile.</p></div><CircleUserRound className="hidden text-slate-400 sm:block" /></header>
    {data.error && <p className="mb-5 rounded-xl border border-rose-400/20 bg-rose-400/10 px-4 py-3 text-sm text-rose-200">{data.error}</p>}
    <p className="mb-5 rounded-xl border border-cyan-300/15 bg-cyan-300/[0.04] px-4 py-3 text-sm text-slate-300">No manual staff creation here. Review applicants under Member Applications.</p>
    <section className="overflow-visible rounded-2xl border border-white/10 bg-[#0b1d34]"><div className="border-b border-white/[0.07] p-4 sm:p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="font-semibold text-white">Staff members</h2><p className="mt-1 text-xs text-slate-500">{filtered.length} matching staff member{filtered.length === 1 ? "" : "s"}</p></div><form method="get" className="flex flex-wrap gap-2"><label className="relative"><Search size={14} className="absolute left-2.5 top-2.5 text-slate-500" /><input name="q" defaultValue={query} placeholder="Search name or code" className="w-52 rounded-lg border border-white/10 bg-[#10233d] py-2 pl-8 pr-3 text-xs text-white outline-none focus:border-cyan-300" /></label><select name="account" defaultValue={account} className="rounded-lg border border-white/10 bg-[#10233d] px-2.5 py-2 text-xs text-white"><option value="">All accounts</option><option value="claimed">Claimed</option><option value="unclaimed">Unclaimed</option></select><button className="rounded-lg bg-blue-600 px-3 py-2 text-xs font-medium text-white hover:bg-blue-500">Filter</button></form></div></div>
      {rows.length ? <div className="divide-y divide-white/[0.06]">{rows.map((row) => { const hasRfid = row.credentials.some((credential) => credential.credential_type === "staff_rfid" && credential.is_active); const credentialLabel = hasRfid && row.camera_enabled ? "RFID + Camera" : hasRfid ? "RFID only" : row.camera_enabled ? "Camera only" : "No credentials"; return <div key={row.id} className="flex flex-wrap items-center justify-between gap-4 px-4 py-4 sm:px-5"><div className="min-w-[220px] flex-1"><p className="font-medium text-white">{row.display_name}</p><p className="mt-1 text-xs text-slate-500">{row.employee_code ?? "No employee code"} · {row.warehouse_name}</p></div><div className="flex flex-wrap items-center gap-2 text-[11px]"><Badge active={row.profile_id !== null} yes="CLAIMED" no="UNCLAIMED" /><span className="rounded-full bg-indigo-500/15 px-2.5 py-1 text-indigo-200">{credentialLabel}</span><StaffPermissionInlineManager staff={row} /><AccountClaimManager kind="staff" targetId={row.id} profileId={row.profile_id} claim={row.account_claim} invokeAction={invokeStaffAccountRequest} revokeAction={revokeStaffAccountRequest} applicantEmail={row.applicant_email} facebookProfileUrl={row.facebook_profile_url} /><Link href={`/staff/${row.id}`} className="inline-flex items-center gap-1 rounded-lg border border-cyan-400/30 px-3 py-2 text-cyan-200 hover:bg-cyan-400/10">Manage <ArrowRight size={13} /></Link></div></div>; })}</div> : <div className="px-5 py-16 text-center text-sm text-slate-400">{data.configured ? "No matching staff members." : "Connect Supabase to load staff members."}</div>}
      <div className="flex items-center justify-between border-t border-white/[0.07] px-5 py-4 text-xs text-slate-400"><span>Page {Math.min(page, pageCount)} of {pageCount}</span><div className="flex gap-2"><Link href={page > 1 ? pageLink(page - 1) : "#"} className={`rounded-lg border border-white/10 px-3 py-2 ${page <= 1 ? "pointer-events-none opacity-40" : "hover:bg-white/5"}`}>Previous</Link><Link href={page < pageCount ? pageLink(page + 1) : "#"} className={`rounded-lg border border-white/10 px-3 py-2 ${page >= pageCount ? "pointer-events-none opacity-40" : "hover:bg-white/5"}`}>Next</Link></div></div>
    </section>
  </>;
}
function Badge({ active, yes, no }: { active: boolean; yes: string; no: string }) { return <span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 ${active ? "bg-emerald-500/20 text-emerald-300" : "bg-slate-500/20 text-slate-400"}`}>{active ? <CheckCircle2 size={12} /> : <XCircle size={12} />}{active ? yes : no}</span>; }
