"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { Bell, CalendarDays, ChevronDown, ChevronRight, CircleAlert, Clock3, DoorOpen, Droplets, LayoutDashboard, Menu, Monitor, Package, Radio, Settings, Shield, ShieldAlert, Thermometer, Truck, Users, Wind } from "lucide-react";
import { ActivityChart } from "./activity-chart";
import type { DashboardData } from "@/lib/dashboard-data";
import { SignOutButton } from "./sign-out-button";
import { RenameWarehouseForm } from "./rename-warehouse-form";
import type { RenameWarehouseState } from "@/app/warehouse/actions";
import { WareGuardLogo } from "./wareguard-logo";

const nav = [["Overview", "/", LayoutDashboard], ["Access Logs", "/access-logs", Clock3], ["Staff & Credentials", "/staff", Users], ["Drivers", "/drivers", Truck], ["Areas & Permissions", "/areas", Radio], ["Safety Monitoring", "/safety", Shield], ["Emergency Status", "/emergency", ShieldAlert], ["Device Management", "/devices", Monitor], ["Trucks", "/trucks", Truck], ["Settings", "/settings", Settings]] as const;
const titleCase = (value: string | undefined) => value?.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()) ?? "Unknown area";
const time = (value: string) => new Date(value).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });

export function DashboardOverview({ data, renameAction }: { data: DashboardData; renameAction: (state: RenameWarehouseState, formData: FormData) => Promise<RenameWarehouseState> }) {
  const [menuOpen, setMenuOpen] = useState(false);
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [now, setNow] = useState(new Date());
  useEffect(() => { const id = window.setInterval(() => setNow(new Date()), 1000); return () => window.clearInterval(id); }, []);
  const status = data.warehouseStatus === "danger" ? "Danger" : data.warehouseStatus === "warning" ? "Warning" : "Normal";
  const roleLabel = data.role === "father_admin" ? "Father Admin" : data.role === "system_admin" ? "System Admin" : "Administrator";
  return <div className="min-h-screen bg-[#061223] text-slate-100">
    <aside className={`fixed inset-y-0 left-0 z-30 flex w-[230px] flex-col border-r border-white/[0.07] bg-[#07182c] px-3 py-5 transition-transform lg:translate-x-0 ${sidebarOpen ? "translate-x-0" : "-translate-x-full"}`}>
      <div className="px-2 pb-7"><WareGuardLogo /></div>
      <nav className="space-y-1">{[...nav, ...(data.role === "father_admin" ? [["System Admin Management", "/admin/system-admins", Users] as const] : [])].map(([label, href, Icon]) => <Link key={label} href={href} onClick={() => setSidebarOpen(false)} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-[13px] transition ${href === "/" ? "bg-blue-600/35 text-white" : "text-slate-300 hover:bg-white/5 hover:text-white"}`}><Icon size={18} strokeWidth={1.8} /><span>{label}</span></Link>)}</nav>
      <div className="mt-auto space-y-4"><div className="rounded-xl border border-white/[0.06] bg-white/[0.035] p-3"><p className="mb-2 text-[11px] text-slate-400">Warehouse</p><select className="w-full rounded-lg border border-white/[0.06] bg-[#10233d] px-2 py-2 text-xs text-slate-200 outline-none" defaultValue={data.selectedWarehouseId ?? ""} disabled={!data.warehouses.length}>{data.warehouses.length ? data.warehouses.map((item) => <option key={item.id} value={item.id}>{item.name}</option>) : <option value="">Main Warehouse</option>}</select>{data.role === "system_admin" && data.selectedWarehouseId && data.warehouses[0] && <RenameWarehouseForm warehouseId={data.selectedWarehouseId} currentName={data.warehouses[0].name} action={renameAction} />}</div><div className="flex items-center justify-between px-2 text-[10px] text-slate-500"><span>WareGuard<br /><span className="text-slate-600">v1.0.0</span></span><span className="flex items-center gap-1.5 text-emerald-400"><span className="h-2 w-2 rounded-full bg-emerald-400" />{data.configured ? "Connected" : "Not configured"}</span></div></div>
    </aside>
    {sidebarOpen && <button aria-label="Close navigation" className="fixed inset-0 z-20 bg-black/60 lg:hidden" onClick={() => setSidebarOpen(false)} />}
    <main className="lg:pl-[230px]"><header className="flex h-[70px] items-center justify-between border-b border-white/[0.07] px-5 sm:px-8"><div className="flex items-center gap-3"><button aria-label="Open navigation" className="text-slate-300 lg:hidden" onClick={() => setSidebarOpen(true)}><Menu size={22} /></button><div className="hidden h-10 w-10 items-center justify-center rounded-full border border-blue-300/20 bg-blue-400/5 sm:flex"><Package size={18} className="text-blue-300" /></div><div><h1 className="text-sm font-semibold text-white sm:text-base">Good afternoon, {data.displayName}</h1><p className="hidden text-[11px] text-slate-400 sm:block">Here&apos;s what&apos;s happening in your warehouse today.</p></div></div><div className="flex items-center gap-4 sm:gap-6"><div className="hidden items-center gap-2 text-right text-[11px] text-slate-300 sm:flex"><CalendarDays size={16} className="text-slate-400" /><span>{now.toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" })}<br />{now.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</span></div><Bell size={19} className="text-slate-300" /><button className="flex items-center gap-2" onClick={() => setMenuOpen(!menuOpen)}><span className="flex h-9 w-9 items-center justify-center rounded-full bg-gradient-to-br from-slate-300 to-slate-500 text-slate-900"><Users size={19} /></span><span className="hidden text-left text-[11px] sm:block"><span className="block font-medium text-white">{data.displayName}</span><span className="text-slate-500">{roleLabel}</span></span><ChevronDown size={14} className="text-slate-400" /></button>{menuOpen && <div className="absolute right-5 top-14 z-20 rounded-xl border border-white/10 bg-[#10233d] px-4 py-3 text-xs text-slate-300 shadow-xl">Account menu<SignOutButton /></div>}</div></header>
      <div className="mx-auto max-w-[1440px] p-5 sm:p-8"><div className="mb-7 flex items-end justify-between"><div><p className="mb-2 text-xs font-medium uppercase tracking-[0.18em] text-cyan-300/80">Operations center</p><h2 className="text-2xl font-semibold tracking-tight text-white sm:text-3xl">Dashboard Overview</h2></div><div className="hidden items-center gap-2 rounded-full border border-white/10 bg-white/[0.03] px-3 py-2 text-xs text-slate-400 sm:flex"><span className="h-2 w-2 rounded-full bg-emerald-400" /> Live overview</div></div>
        {!data.configured && <div className="mb-6 rounded-xl border border-amber-400/20 bg-amber-400/10 px-4 py-3 text-sm text-amber-200">Supabase is not configured for this dashboard. Connect the environment variables to load live warehouse data.</div>}
        <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Stat icon={Users} title="Total Staff" value={data.configured ? String(data.staff.total) : "--"} detail={data.configured ? `Active: ${data.staff.active}   Inactive: ${data.staff.inactive}` : "Not configured"} tone="from-[#102b57] to-[#0d2345]" /><Stat icon={Truck} title="Total Trucks" value={data.configured ? String(data.trucks.total) : "--"} detail={data.configured ? `Active: ${data.trucks.active}   Inactive: ${data.trucks.inactive}` : "Not configured"} tone="from-[#0b393b] to-[#0c292f]" /><Stat icon={DoorOpen} title="Access Today" value={data.configured ? String(data.accessToday.total) : "--"} detail={data.configured ? `Authorized: ${data.accessToday.authorized}   Denied: ${data.accessToday.denied}` : "Not configured"} tone="from-[#282052] to-[#211b43]" /><Stat icon={CircleAlert} title="Safety Events" value={data.configured ? String(data.safetyToday.total) : "--"} detail={data.configured ? `Warnings: ${data.safetyToday.warnings}   Dangers: ${data.safetyToday.dangers}` : "Not configured"} tone="from-[#453014] to-[#302313]" /></div>
        <div className="mt-5 grid gap-5 xl:grid-cols-[1.45fr_1fr_0.8fr]"><section className="rounded-2xl border border-white/10 bg-[#0b1d34] p-4 sm:p-5"><div className="mb-2 flex items-center justify-between"><h3 className="font-semibold text-white">Access Activity <span className="font-normal text-slate-500">(Last 7 Days)</span></h3><div className="flex gap-4 text-[11px]"><span className="flex items-center gap-1.5 text-slate-300"><span className="h-2 w-2 rounded-full bg-emerald-400" />Authorized</span><span className="flex items-center gap-1.5 text-slate-300"><span className="h-2 w-2 rounded-full bg-rose-400" />Denied</span></div></div><ActivityChart data={data.activity} /></section><section className="rounded-2xl border border-white/10 bg-[#0b1d34] p-4 sm:p-5"><h3 className="mb-4 font-semibold text-white">Environment <span className="font-normal text-slate-500">(Latest Reading)</span></h3><Metric icon={Thermometer} label="Temperature" value={data.environment.temperature === null ? "--" : `${data.environment.temperature.toFixed(1)}°C`} tone="text-rose-400 bg-rose-400/10" /><Metric icon={Droplets} label="Humidity" value={data.environment.humidity === null ? "--" : `${data.environment.humidity.toFixed(1)}%`} tone="text-blue-400 bg-blue-400/10" /><Metric icon={Wind} label="Smoke Level" value={data.environment.smoke === null ? "--" : `${data.environment.smoke.toFixed(0)} ppm`} tone="text-cyan-400 bg-cyan-400/10" /><Empty text="Sensor data not available yet. Make sure your devices are connected and configured." /></section><div className="space-y-4"><Status icon={Shield} title="Warehouse Status" value={status} tone="text-emerald-300 bg-emerald-400/15" detail={status === "Normal" ? "All systems operating normally." : "Review unresolved safety events."} /><Status icon={ShieldAlert} title="Emergency Status" value={data.emergency.active ? "Active emergency" : "No active emergency"} tone={data.emergency.active ? "text-rose-300 bg-rose-400/15" : "text-emerald-300 bg-emerald-400/15"} detail={data.emergency.reason ?? (data.emergency.active ? "Immediate attention required." : "Warehouse is in normal operation.")} /><Status icon={Monitor} title="Device Status" value={`${data.devices.filter((device) => device.online).length} / ${data.devices.length} Online`} tone="text-cyan-300 bg-cyan-400/15" detail={data.devices.length ? "Registered devices" : "No devices connected yet."} /></div></div>
        <section className="mt-5 overflow-hidden rounded-2xl border border-white/10 bg-[#0b1d34]"><div className="flex items-center justify-between border-b border-white/[0.07] px-4 py-4 sm:px-5"><h3 className="font-semibold text-white">Recent Access Activity</h3><Link href="/access-logs" className="flex items-center gap-1 text-xs text-cyan-300 hover:text-cyan-200">View All <ChevronRight size={14} /></Link></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-xs"><thead className="bg-white/[0.02] text-slate-500"><tr><th className="px-5 py-3 font-medium">Time</th><th className="px-5 py-3 font-medium">Person / Vehicle</th><th className="px-5 py-3 font-medium">Credential</th><th className="px-5 py-3 font-medium">Area</th><th className="px-5 py-3 font-medium">Result</th><th className="px-5 py-3 font-medium">Reason</th></tr></thead><tbody>{data.recentAccess.map((row) => <tr key={row.id} className="border-t border-white/[0.06] text-slate-300"><td className="px-5 py-4">{time(row.occurred_at)}</td><td className="px-5 py-4"><span className="flex items-center gap-2 text-white">{row.truck_id ? <Truck size={15} className="text-orange-300" /> : <Users size={15} className="text-slate-400" />}{row.truck_id ? data.truckNames[row.truck_id] ?? "Truck" : row.staff_member_id ? data.staffNames[row.staff_member_id] ?? "Staff member" : "Unknown"}</span><span className="ml-5 text-[10px] text-slate-500">{row.truck_id ? "Truck" : row.staff_member_id ? "Staff" : "Unknown"}</span></td><td className="px-5 py-4"><span className="rounded-full bg-indigo-500/25 px-3 py-1 text-[11px] text-indigo-200">{row.authentication_method.replace("staff_", "").replace("truck_", "").toUpperCase()}</span></td><td className="px-5 py-4">{titleCase(data.areas[row.area_id ?? ""])}</td><td className="px-5 py-4"><span className={`rounded-full px-3 py-1 text-[11px] ${row.result === "success" ? "bg-emerald-500/20 text-emerald-300" : "bg-rose-500/20 text-rose-300"}`}>{row.result === "success" ? "Authorized" : "Denied"}</span></td><td className="px-5 py-4 text-slate-500">{typeof row.metadata?.reason === "string" ? row.metadata.reason : "-"}</td></tr>)}</tbody></table>{!data.recentAccess.length && <Empty text={data.configured ? "No access activity recorded yet." : "Connect Supabase to load access activity."} />}</div></section>
        <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Action href="/access-logs" icon={Clock3} label="View Access Logs" /><Action href="/staff" icon={Users} label="Manage Staff" /><Action href="/safety" icon={Shield} label="Safety Monitoring" /><Action href="/devices" icon={Monitor} label="Device Management" /></div>
      </div></main>
  </div>;
}

function Stat({ icon: Icon, title, value, detail, tone }: { icon: typeof Users; title: string; value: string; detail: string; tone: string }) { return <div className={`rounded-2xl border border-white/10 bg-gradient-to-br ${tone} p-5 shadow-xl shadow-black/10`}><div className="mb-4 flex h-11 w-11 items-center justify-center rounded-xl bg-white/10 text-white"><Icon size={23} /></div><p className="text-sm text-slate-300">{title}</p><p className="mt-1 text-3xl font-semibold text-white">{value}</p><p className="mt-2 text-xs text-slate-300">{detail}</p></div>; }
function Metric({ icon: Icon, label, value, tone }: { icon: typeof Thermometer; label: string; value: string; tone: string }) { return <div className="flex items-center gap-3 border-b border-white/[0.06] py-3"><span className={`flex h-9 w-9 items-center justify-center rounded-full ${tone}`}><Icon size={18} /></span><span className="flex-1 text-sm text-slate-300">{label}</span><span className="font-medium text-white">{value}</span><span className="rounded-full bg-white/[0.06] px-2 py-1 text-[10px] text-slate-400">{value === "--" ? "No data" : "Latest"}</span></div>; }
function Empty({ text }: { text: string }) { return <div className="mt-3 rounded-xl bg-[#132945] px-4 py-3 text-[11px] leading-5 text-slate-400">{text}</div>; }
function Status({ icon: Icon, title, value, tone, detail }: { icon: typeof Shield; title: string; value: string; tone: string; detail: string }) { return <div className="rounded-2xl border border-white/10 bg-[#0b1d34] p-4"><div className="flex items-center gap-3"><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${tone}`}><Icon size={21} /></span><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><h3 className="text-sm font-semibold text-white">{title}</h3><ChevronRight size={16} className="text-slate-500" /></div><p className="mt-1 text-xs text-slate-300">{value}</p></div></div><p className="mt-3 pl-[52px] text-[11px] text-slate-500">{detail}</p></div>; }
function Action({ href, icon: Icon, label }: { href: string; icon: typeof Clock3; label: string }) { return <Link href={href} className="flex items-center justify-between rounded-2xl border border-white/10 bg-[#0b1d34] p-4 text-sm text-slate-200 transition hover:border-cyan-300/30 hover:bg-[#102640]"><span className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-cyan-400/10 text-cyan-300"><Icon size={18} /></span>{label}</span><ChevronRight size={16} className="text-slate-500" /></Link>; }
