"use client";

import { useActionState } from "react";
import { submitMemberApplication, type MemberApplicationState } from "@/app/register/actions";

const initialState: MemberApplicationState = { success: false, message: "" };

export function MemberApplicationForm({ role, label }: { role: "staff" | "guard" | "driver"; label: string }) {
  const [state, formAction, pending] = useActionState(submitMemberApplication, initialState);
  return <form action={formAction} className="space-y-4"><input type="hidden" name="requestedRole" value={role} /><label className="block text-sm text-slate-300">Full name<input name="applicantName" required disabled={pending} className="mt-2 w-full rounded-lg border border-white/10 bg-[#10233d] px-3 py-3 text-white outline-none focus:border-cyan-300" /></label><label className="block text-sm text-slate-300">Email<input name="email" type="email" required disabled={pending} className="mt-2 w-full rounded-lg border border-white/10 bg-[#10233d] px-3 py-3 text-white outline-none focus:border-cyan-300" /></label><label className="block text-sm text-slate-300">Exact warehouse full name<input name="warehouseName" required disabled={pending} placeholder="Must exactly match the warehouse name" className="mt-2 w-full rounded-lg border border-white/10 bg-[#10233d] px-3 py-3 text-white outline-none focus:border-cyan-300" /></label><label className="block text-sm text-slate-300">Valid ID link<input name="validIdUrl" type="url" pattern="https://.*" required disabled={pending} placeholder="https://..." className="mt-2 w-full rounded-lg border border-white/10 bg-[#10233d] px-3 py-3 text-white outline-none focus:border-cyan-300" /></label><label className="block text-sm text-slate-300">Facebook profile link<input name="facebookProfileUrl" type="url" pattern="https://(www\.)?facebook\.com/.*" required disabled={pending} placeholder="https://facebook.com/..." className="mt-2 w-full rounded-lg border border-white/10 bg-[#10233d] px-3 py-3 text-white outline-none focus:border-cyan-300" /></label>{role === "driver" && <p className="rounded-lg border border-white/10 bg-white/[0.03] p-3 text-xs leading-5 text-slate-400">Drivers use their assigned truck plate. Face photos and truck RFID are not required.</p>}{role === "staff" && <p className="rounded-lg border border-cyan-300/15 bg-cyan-300/[0.04] p-3 text-xs leading-5 text-slate-400">Staff use one RFID credential at the Staff Main Entrance.</p>}<button type="submit" disabled={pending} className="w-full rounded-lg bg-cyan-500 px-4 py-3 font-semibold text-slate-950 hover:bg-cyan-400 disabled:opacity-60">{pending ? "Submitting..." : `Apply as ${label}`}</button>{state.message && <p role="status" className={`text-sm ${state.success ? "text-emerald-300" : "text-rose-300"}`}>{state.message}</p>}</form>;
}
