import Link from "next/link";
import { Activity, Camera, CheckCircle2, ChevronRight, CircleAlert, Droplets, Flame, Gauge, Monitor, ShieldCheck, Thermometer, Truck, Users, Wind } from "lucide-react";
import type { DashboardData } from "@/lib/dashboard-data";
import { OverviewCameraCard } from "./overview-camera-card";
import { OverviewLiveRefresh } from "./overview-live-refresh";
import { SafetyStatusCard } from "./safety-status-card";

export function OverviewWorkspace({ data }: { data: DashboardData }) {
  const hasWarehouse = data.warehouses.length > 0;
  const onlineDevices = data.devices.filter((device) => device.online).length;
  const currentReading = data.environment.recordedAt && Date.now() - new Date(data.environment.recordedAt).getTime() < 120000;
  const operational = hasWarehouse && (currentReading || onlineDevices > 0);
  const cameraUrl = process.env.CAMERA_TUNNEL_URL ?? "http://127.0.0.1:5001";
  return <>
    <header className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-cyan-300/80">Security Operations</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-white sm:text-4xl">Overview</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">Live warehouse environment, staff RFID access, truck plate camera, and device status in one view.</p></div><OverviewLiveRefresh /></header>
    {!data.configured && <div className="mb-5 rounded-xl border border-amber-300/20 bg-amber-300/10 px-4 py-3 text-sm text-amber-200">Waiting for the warehouse connection.</div>}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
      <OverviewMetric icon={Thermometer} label="Temperature" value={data.environment.temperature == null ? "—" : `${data.environment.temperature}°C`} detail="Roll Yard" state={currentReading ? stateLabel(data.environment.temperatureState) : "Offline"} danger={data.environment.temperatureState === "DANGER"} warning={data.environment.temperatureState === "WARNING"} />
      <OverviewMetric icon={Droplets} label="Humidity" value={data.environment.humidity == null ? "—" : `${data.environment.humidity}%`} detail="Roll Yard" state={currentReading ? stateLabel(data.environment.humidityState) : "Offline"} danger={data.environment.humidityState === "DANGER"} warning={data.environment.humidityState === "WARNING"} meter={data.environment.humidity} />
      <OverviewMetric icon={Wind} label="Smoke / Gas" value={data.environment.smoke == null ? "—" : `${data.environment.smoke}`} detail="Roll Yard" state={data.environment.fireState === "ON" ? "FIRE ON" : currentReading ? stateLabel(data.environment.smokeState) : "Offline"} danger={data.environment.fireState === "ON" || data.environment.smokeState === "DANGER"} warning={data.environment.fireState !== "ON" && data.environment.smokeState === "WARNING"} />
      {data.role === "driver" ? <OverviewMetric icon={Truck} label="My Truck Plate Access" value={`${data.plateAccessToday} granted`} detail="Assigned truck plate grants today" state={hasWarehouse ? "Active" : "Offline"} /> : <OverviewMetric icon={ShieldCheck} label="RFID Staff Access" value={`${data.staffAccessToday} granted`} detail="Staff RFID grants today" state={hasWarehouse ? "Active" : "Offline"} />}
      <OverviewMetric icon={Camera} label="Truck Plate Camera" value={data.role === "system_admin" || data.role === "driver" ? `${data.plateAccessToday} granted` : "Restricted"} detail="Plate access today" state={data.role === "system_admin" || data.role === "driver" ? "Available" : "No access"} />
    </section>
    <section className="mt-5 rounded-2xl border border-white/10 bg-[#0b1d34] p-4 shadow-xl shadow-black/10 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-cyan-400/10 text-cyan-300"><Monitor size={22} /></span><div><h2 className="text-lg font-semibold text-white">Warehouse Monitoring</h2><p className="text-sm text-slate-400">Live status of the hardware already connected to this warehouse.</p></div></div><span className={`rounded-full px-3 py-1.5 text-xs ${operational ? "bg-emerald-400/10 text-emerald-200" : "bg-amber-400/10 text-amber-200"}`}><span className="mr-1.5">●</span>{operational ? "Live" : "Waiting for hardware"}</span></div><div className="mt-5 grid gap-4 xl:grid-cols-[1.25fr_0.8fr_0.8fr]">
      {data.role === "system_admin" ? <OverviewCameraCard cameraUrl={cameraUrl} /> : <EnvironmentCard data={data} />}
      <DeviceStatus data={data} />
      <RecentEvents data={data} />
    </div><div className="mt-4"><SafetyStatusCard environment={data.environment} /></div></section>
    <div className="mt-5 grid gap-4 md:grid-cols-3"><QuickLink href="/access-logs" icon={Activity} title="Access Logs" detail={`${data.accessToday.total} events today`} /><QuickLink href="/sensor-readings" icon={Gauge} title="Sensor Logs" detail={data.environment.triggerReason ?? "View sensor history"} />{data.role === "system_admin" && <QuickLink href="/security-channels" icon={Camera} title="Camera Details" detail="Open full truck camera view" />}</div>
  </>;
}

function OverviewMetric({ icon: Icon, label, value, detail, state, danger, warning, meter }: { icon: typeof Thermometer; label: string; value: string; detail: string; state: string; danger?: boolean; warning?: boolean; meter?: number | null }) { const meterValue = meter == null ? null : Math.max(0, Math.min(100, meter)); return <article className="rounded-2xl border border-cyan-300/10 bg-[#0b1d34] p-4"><div className="flex items-start justify-between gap-2"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-cyan-400/10 text-cyan-300"><Icon size={21} /></span><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wide ${danger ? "bg-rose-400/15 text-rose-200" : warning ? "bg-amber-400/15 text-amber-200" : state === "Offline" ? "bg-slate-400/10 text-slate-400" : "bg-emerald-400/10 text-emerald-200"}`}>{state}</span></div><p className="mt-4 text-xs text-slate-500">{label}</p><p className={`mt-1 text-2xl font-semibold ${danger ? "text-rose-200" : warning ? "text-amber-100" : "text-white"}`}>{value}</p>{meterValue != null && <div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/[0.08]"><div className={`h-full rounded-full transition-all ${danger ? "bg-rose-400" : warning ? "bg-amber-400" : "bg-cyan-400"}`} style={{ width: `${meterValue}%` }} /></div>}<p className="mt-1 text-[11px] text-slate-500">{detail}</p></article>; }
function stateLabel(state: "NORMAL" | "WARNING" | "DANGER" | null) { return state === "DANGER" ? "DANGER" : state === "WARNING" ? "WARNING" : "NORMAL"; }
function EnvironmentCard({ data }: { data: DashboardData }) { return <section className="rounded-2xl border border-white/[0.07] bg-[#10233d] p-4"><h3 className="font-semibold text-white">Environment</h3><p className="mt-1 text-xs text-slate-500">Latest Roll Yard reading</p><div className="mt-4 space-y-1"><Mini icon={Thermometer} label="Temperature" value={data.environment.temperature == null ? "—" : `${data.environment.temperature}°C`} /><Mini icon={Droplets} label="Humidity" value={data.environment.humidity == null ? "—" : `${data.environment.humidity}%`} /><Mini icon={Wind} label="Smoke / gas" value={data.environment.smoke == null ? "—" : String(data.environment.smoke)} /><Mini icon={Flame} label="Fire state" value={data.environment.fireState ?? "OFF"} danger={data.environment.fireState === "ON"} /></div><p className="mt-3 rounded-xl bg-[#132945] px-3 py-2 text-xs text-slate-400">{data.environment.triggerReason ?? "No active event"}</p></section>; }
function DeviceStatus({ data }: { data: DashboardData }) { return <section className="rounded-2xl border border-white/[0.07] bg-[#10233d] p-4"><h3 className="font-semibold text-white">Device Status</h3><p className="mt-1 text-xs text-slate-500">Online/offline from last heartbeat</p><div className="mt-3 space-y-2">{data.devices.length ? data.devices.slice(0, 5).map((device) => <div key={device.id} className="flex items-center gap-3 rounded-xl bg-white/[0.03] px-3 py-2.5"><span className={`h-2.5 w-2.5 rounded-full ${device.online ? "bg-emerald-300 shadow-[0_0_10px_rgba(110,231,183,0.8)]" : "bg-rose-300"}`} /><span className="min-w-0 flex-1 truncate text-xs text-slate-300">{device.name}</span><span className={`text-[11px] ${device.online ? "text-emerald-300" : "text-rose-300"}`}>{device.online ? "Online" : "Offline"}</span></div>) : <p className="py-8 text-center text-xs text-slate-500">No registered devices.</p>}</div><p className="mt-3 text-[11px] text-slate-500">{data.devices.length ? `${data.devices.filter((device) => device.online).length} online · ${data.devices.filter((device) => !device.online).length} offline` : "Connect a device to begin"}</p></section>; }
function RecentEvents({ data }: { data: DashboardData }) { return <section className="rounded-2xl border border-white/[0.07] bg-[#10233d] p-4"><div className="flex items-center justify-between"><h3 className="font-semibold text-white">Recent Events</h3><Link href="/access-logs" className="text-cyan-300"><ChevronRight size={16} /></Link></div><div className="mt-3 space-y-3">{data.recentAccess.slice(0, 4).map((row) => <div key={row.id} className="border-b border-white/[0.06] pb-3"><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${row.result === "success" ? "bg-emerald-300" : "bg-rose-300"}`} /><p className="truncate text-xs text-slate-200">{row.result === "success" ? "Access granted" : "Access denied"}</p><time className="ml-auto text-[10px] text-slate-500">{new Date(row.occurred_at).toLocaleTimeString("en-PH", { timeZone: "Asia/Manila", hour: "2-digit", minute: "2-digit" })}</time></div><p className="mt-1 truncate pl-4 text-[11px] text-slate-500">{row.authentication_method.replaceAll("_", " ")}</p></div>)}{!data.recentAccess.length && <p className="py-8 text-center text-xs text-slate-500">No recent access events.</p>}</div></section>; }
function Mini({ icon: Icon, label, value, danger }: { icon: typeof Thermometer; label: string; value: string; danger?: boolean }) { return <div className="flex items-center gap-3 border-b border-white/[0.06] py-2.5"><Icon size={16} className="text-cyan-300" /><span className="flex-1 text-xs text-slate-400">{label}</span><span className={danger ? "text-rose-200" : "text-white"}>{value}</span></div>; }
function QuickLink({ href, icon: Icon, title, detail }: { href: string; icon: typeof Activity; title: string; detail: string }) { return <Link href={href} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-[#0b1d34] p-4 transition hover:border-cyan-300/30 hover:bg-cyan-400/[0.05]"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-cyan-400/10 text-cyan-300"><Icon size={19} /></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold text-white">{title}</span><span className="mt-1 block truncate text-xs text-slate-500">{detail}</span></span><ChevronRight size={17} className="text-slate-500" /></Link>; }
