import { Activity, Flame, Gauge, Radio, Thermometer } from "lucide-react";
import { loadAreasData, type RoomEnvironmentConfig } from "@/lib/areas-data";
import { createClient } from "@/lib/supabase/server";

type LatestReading = { area_id: string; recorded_at: string; temperature_c: number | null; humidity_pct: number | null; smoke_value: number | null; fire_state: "ON" | "OFF" | null; trigger_reason: string | null };

export default async function SensorDemoPage() {
  const data = await loadAreasData();
  const rooms = data.areas.filter((area) => area.area_type_code === "room");
  const latestReadings = await loadLatestReadings(rooms.map((room) => room.id));
  return <>
    <header className="mb-8"><p className="text-xs font-medium uppercase tracking-[0.2em] text-cyan-300/80">Hardware Preparation</p><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-semibold text-white">Sensor Demo</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Room readings will appear here after the real IoT hardware connects. The limit summary below comes from Room Sensor Settings.</p></div><span className="rounded-full border border-amber-300/20 bg-amber-300/10 px-3 py-2 text-xs text-amber-200">Waiting for hardware</span></div></header>
    {data.error && <p className="mb-5 rounded-xl border border-rose-400/20 bg-rose-400/10 px-4 py-3 text-sm text-rose-200">{data.error}</p>}
    {!rooms.length && !data.error && <section className="rounded-2xl border border-dashed border-white/10 bg-[#0b1d34] px-6 py-16 text-center"><Radio className="mx-auto text-cyan-300" size={28} /><h2 className="mt-4 text-lg font-semibold text-white">Create a Room first</h2><p className="mt-2 text-sm text-slate-500">The hardware demo is organized by Room.</p></section>}
    {!!rooms.length && <div className="space-y-5">{rooms.map((room) => { const reading = latestReadings.get(room.id); return <section key={room.id} className="rounded-2xl border border-cyan-300/15 bg-[#0b1d34] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[0.16em] text-cyan-300/80">Room sensor preview</p><h2 className="mt-1 text-xl font-semibold text-white">{room.name}</h2></div><span className={reading ? "text-xs text-emerald-300" : "text-xs text-slate-500"}>{reading ? `Last reading ${new Date(reading.recorded_at).toLocaleString()}` : "No hardware reading"}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><DemoMetric icon={<Thermometer size={18} />} label="Temperature" value={reading?.temperature_c == null ? "— °C" : `${reading.temperature_c} °C`} /><DemoMetric icon={<Gauge size={18} />} label="Humidity" value={reading?.humidity_pct == null ? "— %" : `${reading.humidity_pct} %`} /><DemoMetric icon={<Activity size={18} />} label="Smoke / gas" value={reading?.smoke_value == null ? "—" : String(reading.smoke_value)} /><DemoMetric icon={<Flame size={18} />} label="Fire state" value={reading?.fire_state ?? "OFF"} /><div className="rounded-xl border border-white/[0.07] bg-[#10233d] p-4"><p className="text-xs text-slate-500">Trigger reason</p><p className="mt-2 text-sm font-medium text-slate-400">{reading?.trigger_reason ?? "No active event"}</p></div></div><ThresholdSummary config={room.environment_config} /><p className="mt-4 text-xs text-slate-500">Values shown here come only from the real device through the sensor-reading Edge Function.</p></section>; })}</div>}
  </>;
}

async function loadLatestReadings(roomIds: string[]) { const latest = new Map<string, LatestReading>(); if (!roomIds.length) return latest; const client = await createClient(); const { data } = await client.from("sensor_readings").select("area_id,recorded_at,temperature_c,humidity_pct,smoke_value,fire_state,trigger_reason").in("area_id", roomIds).order("recorded_at", { ascending: false }).limit(500); for (const row of (data ?? []) as LatestReading[]) if (!latest.has(row.area_id)) latest.set(row.area_id, row); return latest; }

function ThresholdSummary({ config }: { config: RoomEnvironmentConfig | null }) { const shown = (value: number | null | undefined, suffix = "") => value === null || value === undefined ? "—" : `${value}${suffix}`; return <div className="mt-4 rounded-xl border border-white/[0.07] bg-[#10233d]/70 p-4"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-cyan-200">Configured limits for this room</p><div className="mt-3 grid gap-3 text-xs sm:grid-cols-3"><div><p className="text-slate-500">Temperature</p><p className="mt-1 text-slate-300">Normal {shown(config?.temperature_min_c, "°C")}–{shown(config?.temperature_max_c, "°C")}</p><p className="mt-1 text-amber-200">Warning {shown(config?.temperature_warning_low_c, "°C")} / {shown(config?.temperature_warning_high_c, "°C")}</p><p className="mt-1 text-rose-200">Danger {shown(config?.temperature_danger_low_c, "°C")} / {shown(config?.temperature_danger_high_c, "°C")}</p></div><div><p className="text-slate-500">Humidity</p><p className="mt-1 text-slate-300">Normal {shown(config?.humidity_min_pct, "%")}–{shown(config?.humidity_max_pct, "%")}</p><p className="mt-1 text-amber-200">Warning {shown(config?.humidity_warning_low_pct, "%")} / {shown(config?.humidity_warning_high_pct, "%")}</p><p className="mt-1 text-rose-200">Danger {shown(config?.humidity_danger_low_pct, "%")} / {shown(config?.humidity_danger_high_pct, "%")}</p></div><div><p className="text-slate-500">Smoke / gas</p><p className="mt-1 text-slate-300">Normal ≤ {shown(config?.smoke_max_value)}</p><p className="mt-1 text-amber-200">Warning ≥ {shown(config?.smoke_warning_value)}</p><p className="mt-1 text-rose-200">Danger ≥ {shown(config?.smoke_danger_value)} · {shown(config?.gas_exposure_seconds, "s")} exposure</p></div></div></div>; }

function DemoMetric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="rounded-xl border border-white/[0.07] bg-[#10233d] p-4"><div className="flex items-center gap-2 text-cyan-200">{icon}<span className="text-xs text-slate-500">{label}</span></div><p className="mt-3 text-xl font-semibold text-white">{value}</p></div>; }
