import { Logs } from "lucide-react";
import { loadAccessLogs } from "@/lib/access-logs-data";

type SearchParams = Promise<Record<string, string | string[] | undefined>>;
function one(value: string | string[] | undefined) { return Array.isArray(value) ? value[0] ?? "" : value ?? ""; }
function label(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function resultLabel(value: string) { return value === "success" ? "Authorized" : value === "denied" ? "Unauthorized" : "No readings"; }
function methodLabel(value: string) { return ({ staff_rfid: "Staff RFID", staff_face: "Face recognition", truck_plate: "Plate recognition" } as Record<string, string>)[value] ?? label(value); }

export default async function AccessLogsPage({ searchParams }: { searchParams: SearchParams }) {
  const params = await searchParams;
  const filters = { page: Math.max(1, Number(one(params.page)) || 1), pageSize: 20, search: one(params.search), result: one(params.result), method: one(params.method), areaId: one(params.areaId), dateFrom: one(params.dateFrom), dateTo: one(params.dateTo) };
  const data = await loadAccessLogs(filters);
  const pageCount = Math.max(1, Math.ceil(data.total / data.pageSize));
  return <>
    <header className="mb-7"><p className="text-xs font-medium uppercase tracking-[0.18em] text-cyan-300/80">Activity & Events</p><h1 className="mt-2 text-3xl font-semibold text-white">Access Logs</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">Door and entrance access events only. Room sensor readings are shown in Sensor Logs.</p></header>
    <form method="get" className="mb-5 rounded-2xl border border-white/10 bg-[#0b1d34] p-4"><div className="grid gap-3 xl:grid-cols-[1fr_1fr_1fr_1fr_auto]"><select name="result" defaultValue={filters.result} className="rounded-lg border border-white/10 bg-[#10233d] px-3 py-2.5 text-sm text-white"><option value="">All results</option><option value="authorized">Authorized</option><option value="unauthorized">Unauthorized</option><option value="no_readings">No readings</option></select>{data.role !== "driver" ? <select name="method" defaultValue={filters.method} className="rounded-lg border border-white/10 bg-[#10233d] px-3 py-2.5 text-sm text-white"><option value="">All methods</option><option value="staff_rfid">Staff RFID</option><option value="staff_face">Face recognition</option><option value="truck_plate">Plate recognition</option></select> : <input type="hidden" name="method" value="truck_plate" />}<select name="areaId" defaultValue={filters.areaId} className="rounded-lg border border-white/10 bg-[#10233d] px-3 py-2.5 text-sm text-white"><option value="">All entrance areas</option>{data.areas.map((area) => <option key={area.id} value={area.id}>{area.name}</option>)}</select><label className="rounded-lg border border-white/10 bg-[#10233d] px-3 py-2 text-xs text-slate-400">From<input name="dateFrom" type="datetime-local" defaultValue={filters.dateFrom} className="mt-1 block w-full bg-transparent text-sm text-white outline-none" /></label><label className="rounded-lg border border-white/10 bg-[#10233d] px-3 py-2 text-xs text-slate-400">To<input name="dateTo" type="datetime-local" defaultValue={filters.dateTo} className="mt-1 block w-full bg-transparent text-sm text-white outline-none" /></label><button className="rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-medium text-white">Apply</button></div></form>
    {data.error && <p className="mb-5 rounded-xl border border-rose-400/20 bg-rose-400/10 px-4 py-3 text-sm text-rose-200">{data.error}</p>}
    <section className="overflow-hidden rounded-2xl border border-white/10 bg-[#0b1d34]"><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-xs"><thead className="bg-white/[0.02] text-slate-500"><tr><th className="px-5 py-3">Date & time</th><th className="px-5 py-3">Identity</th><th className="px-5 py-3">Method</th><th className="px-5 py-3">Area</th><th className="px-5 py-3">Result</th></tr></thead><tbody>{data.rows.map((row) => <tr key={row.id} className="border-t border-white/[0.06] text-slate-300"><td className="whitespace-nowrap px-5 py-4">{new Date(row.occurredAt).toLocaleString("en-PH", { timeZone: "Asia/Manila" })}</td><td className="px-5 py-4 font-medium text-white">{row.personName ?? row.truckName ?? "Unknown"}</td><td className="px-5 py-4">{methodLabel(row.authenticationMethod)}</td><td className="px-5 py-4">{row.areaName ?? "—"}</td><td className="px-5 py-4"><span className={row.result === "success" ? "text-emerald-300" : row.result === "denied" ? "text-rose-300" : "text-amber-300"}>{resultLabel(row.result)}</span></td></tr>)}</tbody></table>{!data.rows.length && <div className="px-5 py-16 text-center"><Logs className="mx-auto text-cyan-300" size={26} /><p className="mt-3 text-sm text-slate-400">No access logs found.</p></div>}</div><div className="flex items-center justify-between border-t border-white/[0.07] px-5 py-4 text-xs text-slate-400"><span>Page {data.page} of {pageCount}</span><div className="flex gap-2"><a href={`/access-logs?page=${Math.max(1, data.page - 1)}`} className="rounded-lg border border-white/10 px-3 py-2">Previous</a><a href={`/access-logs?page=${Math.min(pageCount, data.page + 1)}`} className="rounded-lg border border-white/10 px-3 py-2">Next</a></div></div></section>
  </>;
}
