import { Thermometer } from "lucide-react";
import { loadSensorLogs } from "@/lib/sensor-readings-data";

type SearchParams = Promise<Record<string, string | string[] | undefined>>;
function one(value: string | string[] | undefined) { return Array.isArray(value) ? value[0] ?? "" : value ?? ""; }
function many(value: string | string[] | undefined) { return Array.isArray(value) ? value : value ? [value] : []; }
function label(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }

export default async function SensorLogsPage({ searchParams }: { searchParams: SearchParams }) {
  const params = await searchParams;
  const filters = { status: one(params.status), thresholds: many(params.threshold), areaId: one(params.areaId), dateFrom: one(params.dateFrom), dateTo: one(params.dateTo) };
  const data = await loadSensorLogs(filters);
  return <>
    <header className="mb-7"><p className="text-xs font-medium uppercase tracking-[0.18em] text-cyan-300/80">Activity & Events</p><h1 className="mt-2 text-3xl font-semibold text-white">Sensor Logs</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">Shared room environmental readings and safety states in one timeline for Staff, Guards, Drivers, and System Admin. Refresh to load the latest readings.</p></header>
    <form method="get" className="mb-5 rounded-2xl border border-white/10 bg-[#0b1d34] p-4"><div className="grid gap-3 xl:grid-cols-[1fr_1fr_1fr_1fr_auto]"><select name="status" defaultValue={filters.status} className="rounded-lg border border-white/10 bg-[#10233d] px-3 py-2.5 text-sm text-white"><option value="">All results</option><option value="warning">Warning</option><option value="danger">Danger</option><option value="fire">Fire State</option></select><select name="areaId" defaultValue={filters.areaId} className="rounded-lg border border-white/10 bg-[#10233d] px-3 py-2.5 text-sm text-white"><option value="">All room areas</option>{data.rooms.map((room) => <option key={room.id} value={room.id}>{room.name}</option>)}</select><label className="rounded-lg border border-white/10 bg-[#10233d] px-3 py-2 text-xs text-slate-400">From<input name="dateFrom" type="datetime-local" defaultValue={filters.dateFrom} className="mt-1 block w-full bg-transparent text-sm text-white outline-none" /></label><label className="rounded-lg border border-white/10 bg-[#10233d] px-3 py-2 text-xs text-slate-400">To<input name="dateTo" type="datetime-local" defaultValue={filters.dateTo} className="mt-1 block w-full bg-transparent text-sm text-white outline-none" /></label><button className="rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-medium text-white">Apply</button></div><div className="mt-4 flex flex-wrap items-center gap-4 border-t border-white/[0.07] pt-3"><span className="text-xs font-medium uppercase tracking-wider text-slate-500">All threshold</span>{["temperature", "humidity", "gas"].map((threshold) => <label key={threshold} className="inline-flex items-center gap-2 text-sm text-slate-300"><input type="checkbox" name="threshold" value={threshold} defaultChecked={filters.thresholds.includes(threshold)} className="h-4 w-4 accent-cyan-400" />{label(threshold)}</label>)}</div></form>
    {data.error && <p className="mb-5 rounded-xl border border-rose-400/20 bg-rose-400/10 px-4 py-3 text-sm text-rose-200">{data.error}</p>}
    <section className="overflow-hidden rounded-2xl border border-white/10 bg-[#0b1d34]"><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-xs"><thead className="bg-white/[0.02] text-slate-500"><tr><th className="px-5 py-3">Date & time</th><th className="px-5 py-3">Room</th><th className="px-5 py-3">Temperature</th><th className="px-5 py-3">Humidity</th><th className="px-5 py-3">Gas / smoke</th><th className="px-5 py-3">Fire state</th><th className="px-5 py-3">Trigger reason</th></tr></thead><tbody>{data.rows.map((row) => <tr key={row.id} className="border-t border-white/[0.06] text-slate-300"><td className="whitespace-nowrap px-5 py-4">{new Date(row.recordedAt).toLocaleString("en-PH", { timeZone: "Asia/Manila" })}</td><td className="px-5 py-4 font-medium text-white">{row.roomName}</td><td className="px-5 py-4">{row.temperature === null ? "—" : `${row.temperature} °C`}</td><td className="px-5 py-4">{row.humidity === null ? "—" : `${row.humidity} %`}</td><td className="px-5 py-4">{row.gas ?? "—"}</td><td className="px-5 py-4"><span className={row.fireState === "ON" ? "font-semibold text-rose-300" : "text-emerald-300"}>{row.fireState}</span></td><td className="px-5 py-4 text-slate-400">{row.triggerReason}</td></tr>)}</tbody></table>{!data.rows.length && <div className="px-5 py-16 text-center"><Thermometer className="mx-auto text-cyan-300" size={26} /><p className="mt-3 text-sm text-slate-400">No sensor logs found.</p></div>}</div></section>
  </>;
}
